apiVersion: v1
kind: Service
metadata:
  name: appicaltion-name
spec:
  type: ClusterIP
  selector:
    app: appicaltion-name
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http